### ISSUE TITLE
Issue when connecting with RealVNC Server of Raspberry Pi

### ISSUE THREAD

**Issue by kazemiprince** [zocker-160/pyQVNCWidget#5]
Hope you're fine.
I'm trying to connect to a sever(it's on raspberry pi) but I need to login with username and password but couldn't find how to do it.
trying with password only will give this exception:
`qvncwidget.rfb.RFBHandshakeFailed: b'No configured security type is supported by 3.3 VNC Viewer'`

**Comment by zocker-160** [comment]
kinda known issue: 

Raspberry Pi uses RealVNC Server which sadly does not comply with the RFB 3.3 protocol, because it does enforce an encrypted connection and refuse it otherwise, which according to RFB 3.3 is optional and not required.

This VNC client is actually not the only one with that issue, since even a very known VNC client like Remmina fails to connect to the RealVNC Server shipped with a Raspberry Pi.

Given that this widget does only support the absolute minimum of the RFB specification, this is not going to work without some significant effort to implement an encrypted connection.

**Comment by zocker-160** [comment]
UPDATE:

I actually managed to make it work by changing some settings. This didn't work in the past, so I am a bit surprised.

You need to disable encryption in the options and set the password from UNIX to VNC.

I think I will add a note to the readme mentioning this limitation.

EDIT: after doing a bit of testing, it seems a bit buggy, I will look into that.

**Comment by slevon** [comment]
Hey,
just whated to confirm your solution. I changed the authentication of RealVNC to VNC Password and was able to connect to the RPi. However, I do not get an entire desktop, but only the top bar, that I can interact with. See screenshot
![image](https://user-images.githubusercontent.com/1965636/227719386-91838676-6143-46a1-a54b-ef7fb3002a2b.png)

If you need any more information on that, just let me know.

**Comment by zocker-160** [comment]
Yes I know, as I said in my comment above, it is bugged and I sadly did not have the time to look into it yet.

It works fine with any other VNC server I have tested so far, only RealVNC on the PI has this weird issue.

**Comment by zocker-160** [comment]
fixed in v0.3.x
